name: Bygg og deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  bygg-og-deploy:
    name: Bygg og deploy
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Version
        run: echo "VERSION=$(TZ=\"Europe/Oslo\" date +%Y.%m.%d_%H.%M)-$(git rev-parse --short=12 HEAD)" >> $GITHUB_ENV
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - name: Deploy release
        run: mvn -B -Drevision="${{ env.VERSION }}" source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          prerelease: false
